version: '3.8'

services:
  backend:
    image: your-dockerhub-username/course-app-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure

  frontend:
    image: your-dockerhub-username/course-app-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure 